default: &default
  adapter: postgresql
  encoding: unicode
  # Docker Compose を使用する場合は host: db となりますが、
  # Docker 単体で起動している場合は localhost を使用します。
  host: 127.0.0.1
  port: 5432 # PostgreSQL のデフォルトポート
  username: postgres # Docker でのデフォルトユーザー名
  password: Haru-0528
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_mahjong_app_development # 開発用データベース名

test:
  <<: *default
  database: my_mahjong_app_test # テスト用データベース名

production:
  <<: *default
  database: my_mahjong_app_production
  username: <%= ENV['MY_MAHJONG_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['MY_MAHJONG_APP_DATABASE_PASSWORD'] %>